#!/bin/bash

[ -n "$VERBOSE" ] && echo "postinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    configure)

    rm -f __PREFIX__/lib/kafka-schema-registry-client*.jar
    rm -f __PREFIX__/lib/kafka-connect-avro-converter*.jar
    rm -f __PREFIX__/lib/kafka-avro-serializer*.jar
    newJar=$(find __INSTALL_3DIGIT__/share/java/schema-registry/   -printf '%T+ %p\n'   | sort -r | grep kafka-schema-registry-client |  head -n 1 |  awk '{ print $2 }')
    ln -sf $newJar  __PREFIX__/lib/.
    newJarAvroConverter=$(find __INSTALL_3DIGIT__/share/java/schema-registry/   -printf '%T+ %p\n'   | sort -r | grep kafka-connect-avro-converter |  head -n 1 |  awk '{ print $2 }')
    ln -sf $newJarAvroConverter  __PREFIX__/lib/.
    newJarAvroSerializer=$(find __INSTALL_3DIGIT__/share/java/schema-registry/   -printf '%T+ %p\n'   | sort -r | grep kafka-avro-serializer |  head -n 1 |  awk '{ print $2 }')
    ln -sf $newJarAvroSerializer  __PREFIX__/lib/.

	#
	# change permissions
	#
	DAEMON_CONF=__PREFIX__/conf/daemon.conf
	if [ -f "$DAEMON_CONF" ]; then
    		MAPR_USER=$( awk -F = '$1 == "mapr.daemon.user" { print $2 }' $DAEMON_CONF)
    		MAPR_GROUP=$( awk -F = '$1 == "mapr.daemon.group" { print $2 }' $DAEMON_CONF)
    		if [ ! -z "$MAPR_USER" ]; then
        		chown -R ${MAPR_USER} __PREFIX__/schema-registry/
    		fi
    		if [ ! -z "$MAPR_GROUP" ]; then
        		chgrp -R ${MAPR_GROUP} __PREFIX__/schema-registry/
    		fi
	fi

	mkdir -p "__INSTALL_3DIGIT__"/logs
	chmod 1777 "__INSTALL_3DIGIT__"/logs
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac