#!/bin/bash

[ -n "$VERBOSE" ] && echo "prerm called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    remove|upgrade|deconfigure)

     if [ -f  __PREFIX__/schema-registry/schema-registryversion ]; then
        bash __PREFIX__/schema-registry/schema-registry-__VERSION_3DIGIT__/bin/schema-registry-stop-service
     fi

     if [ -d __PREFIX__/schema-registry/schema-registry-__VERSION_3DIGIT__/logs ]; then
        rm -rf __PREFIX__/schema-registry/schema-registry-__VERSION_3DIGIT__/logs
     fi

     rm -f __PREFIX__/lib/kafka-schema-registry-client*.jar
     rm -f __PREFIX__/lib/kafka-connect-avro-converter*.jar
     rm -f __PREFIX__/lib/kafka-avro-serializer*.jar

    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac